#!/usr/bin/env python3
"""
Generate the Expo-ready icon set in brand-drafts/expo-ready/.

These files are formatted for Expo's build pipeline. To deploy:

    cp brand-drafts/expo-ready/icon.png         assets/icon.png
    cp brand-drafts/expo-ready/adaptive-icon.png assets/adaptive-icon.png
    cp brand-drafts/expo-ready/splash-icon.png  assets/splash-icon.png
    cp brand-drafts/expo-ready/favicon.png      assets/favicon.png

NOT auto-copied — that commits to Concept E without explicit
approval. Drafts only until Isaac picks an icon direction.

What each file is for:
  icon.png         1024x1024 — App Store, all iOS contexts
  adaptive-icon.png 1024x1024 — Android adaptive icon FOREGROUND. The
                                bead is centered in the inner 66%
                                "safe zone" so Android's circle /
                                rounded-square / squircle masks don't
                                clip it. Background color is set in
                                app.json (`expo.android.adaptiveIcon
                                .backgroundColor` = "#0F0E1A").
  splash-icon.png  1024x1024 — Expo splash plugin centers this on
                                splash.backgroundColor.
  favicon.png      48x48     — Expo web favicon (Metro's default).

Source: concept E (Detonation Bead) at 1024x1024. If Isaac picks a
different concept this script needs the SRC constant updated.
"""

from __future__ import annotations

import os
from PIL import Image, ImageDraw, ImageFilter

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "expo-ready")
os.makedirs(OUT_DIR, exist_ok=True)

SRC_ICON = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "icon-e-bead-1024.png",
)

BG_DARK = (15, 14, 26)


def main() -> None:
    if not os.path.exists(SRC_ICON):
        raise SystemExit(
            f"missing source {SRC_ICON}; run generate_icons.py first"
        )
    base = Image.open(SRC_ICON).convert("RGB")

    # icon.png — App Store + iOS. Just a copy at 1024x1024.
    icon_path = os.path.join(OUT_DIR, "icon.png")
    base.save(icon_path, "PNG", optimize=True)
    print(f"wrote {icon_path}")

    # adaptive-icon.png — Android foreground. The bead must sit
    # inside the inner 66% (safe zone) of the 1024x1024 canvas so
    # Android's launcher masks (circle/rounded-square/squircle) don't
    # clip it. Concept E's bead is 58% width centered — already
    # within safe zone, but to be safe we render on a transparent
    # canvas at 80% scale + then composite on the dark background.
    adaptive = Image.new("RGBA", (1024, 1024), (0, 0, 0, 255))
    # Draw the dark background fill
    draw = ImageDraw.Draw(adaptive)
    draw.rectangle([0, 0, 1024, 1024], fill=BG_DARK)
    # Scale the source down to 80% and composite centered — keeps
    # the bead well inside the 66% safe zone with extra margin.
    inner = base.resize((820, 820), Image.LANCZOS)
    adaptive.paste(inner, ((1024 - 820) // 2, (1024 - 820) // 2))
    adaptive_path = os.path.join(OUT_DIR, "adaptive-icon.png")
    adaptive.convert("RGB").save(adaptive_path, "PNG", optimize=True)
    print(f"wrote {adaptive_path}")

    # splash-icon.png — Expo splash plugin. Same as icon.png but
    # symbolically separate so a different splash composition can
    # ship later without touching the App Store icon.
    splash_path = os.path.join(OUT_DIR, "splash-icon.png")
    base.save(splash_path, "PNG", optimize=True)
    print(f"wrote {splash_path}")

    # favicon.png — Expo web. 48x48 is Expo's default, but we'll
    # also write the larger 32 + 64 px variants Expo serves at
    # different DPRs.
    for sz in (32, 48, 64):
        fav = base.resize((sz, sz), Image.LANCZOS)
        path = os.path.join(OUT_DIR, f"favicon-{sz}.png")
        fav.save(path, "PNG", optimize=True)
        print(f"wrote {path}")
    # Also produce the canonical `favicon.png` Expo expects (48x48)
    fav48 = base.resize((48, 48), Image.LANCZOS)
    fav48_path = os.path.join(OUT_DIR, "favicon.png")
    fav48.save(fav48_path, "PNG", optimize=True)
    print(f"wrote {fav48_path}")

    # And write a one-line README so future-Isaac knows how to deploy
    readme_path = os.path.join(OUT_DIR, "README.md")
    with open(readme_path, "w") as f:
        f.write(
            "# Expo-ready CHROMA icon set\n\n"
            "Generated by `brand-drafts/generate_expo_ready.py` from\n"
            "the Concept E (Detonation Bead) source. **NOT yet wired\n"
            "into the production build** — see brand-design-spec.md\n"
            "for the icon-direction decision rationale.\n\n"
            "To deploy once you commit to Concept E:\n\n"
            "```bash\n"
            "cp brand-drafts/expo-ready/icon.png          assets/icon.png\n"
            "cp brand-drafts/expo-ready/adaptive-icon.png assets/adaptive-icon.png\n"
            "cp brand-drafts/expo-ready/splash-icon.png   assets/splash-icon.png\n"
            "cp brand-drafts/expo-ready/favicon.png       assets/favicon.png\n"
            "```\n\n"
            "Then in `app.json` confirm:\n"
            "- `expo.icon` points at `./assets/icon.png` (default already)\n"
            "- `expo.android.adaptiveIcon.backgroundColor` is `#0F0E1A`\n"
            "- `expo.splash.backgroundColor` is `#0F0E1A`\n"
            "- `expo.web.favicon` points at `./assets/favicon.png`\n\n"
            "These all already match expectations — the only step is\n"
            "the `cp` quartet above.\n"
        )
    print(f"wrote {readme_path}")


if __name__ == "__main__":
    main()
